DROP TABLE IF EXISTS PAY_FLOW;
DROP TABLE IF EXISTS ORDER_DETAIL;
DROP TABLE IF EXISTS GOODS_ORDER;
DROP TABLE IF EXISTS INVERTORY;
DROP TABLE IF EXISTS GOODS;
DROP TABLE IF EXISTS STORE;
DROP TABLE IF EXISTS PEOPLE;
DROP TABLE IF EXISTS  LOGISTICS_INFO;
DROP TABLE IF EXISTS  LOGISTICS_GOBY;


-- 人员信息表
-- 人员：主键，姓名，性别，年龄，(地址)，持有金额，身份证号
CREATE TABLE PEOPLE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `NAME` VARCHAR(20) NOT NULL COMMENT '姓名',
  CARD_ID VARCHAR(30) NOT NULL COMMENT '身份证号',
  SEX VARCHAR(4) DEFAULT '男' COMMENT '性别 男 女',
  AGE INT COMMENT '年龄',
	MONEY DECIMAL(15,3) COMMENT '持有金额',
	ADDRESS VARCHAR(64) COMMENT '地址',
	USERNAME  VARCHAR(30) NOT NULL COMMENT '账户',
	PASSWORD  VARCHAR(30) NOT NULL COMMENT '密码',
	PAY_PASSWORD VARCHAR(30) COMMENT '支付密码'
)ENGINE=INNODB  DEFAULT CHARSET=UTF8 COMMENT='人类信息';


-- 商品信息
-- 商品：主键，编号，名称，类型，单位，生产日期，保质期，保质期单位
CREATE TABLE GOODS(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
	GOODS_NUM VARCHAR(32)  COMMENT '商品编号',
	`NAME` VARCHAR(64) COMMENT '商品名字',
	TYPE TINYINT (2) COMMENT '商品类型 0--电脑 1--清洁用品 2--运动器材 3--服装',
	UNIT VARCHAR(32) COMMENT '单位',
	PROCEDURE_DATE DATETIME COMMENT '生产日期 yyyy-MM-dd HH:mm:ss',
	SHELF_LIFE FLOAT COMMENT '保质期',
	SHELF_LIFE_UNIT TINYINT(2) DEFAULT 1 COMMENT '保质期单位 0--小时 1--天 2--月 3--年'
)ENGINE=INNODB  DEFAULT CHARSET=UTF8 COMMENT='商品信息';


-- 店铺信息
-- 店铺：主键，编号，名字，信誉度，所属人员
CREATE TABLE STORE(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
	STORE_NUM VARCHAR (32)  COMMENT '店铺编号',
	STORE_NAME VARCHAR(32)  COMMENT '店铺名称',
	CREDIT BIGINT COMMENT '信誉度',
  PEOPLE_ID BIGINT COMMENT '卖家(人员外键)' REFERENCES PEOPLE(ID),
 	CONSTRAINT FK_PEOPLE_ID FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE(ID)
)ENGINE=INNODB  DEFAULT CHARSET=UTF8 COMMENT='卖家信息';


-- 库存信息
-- 主键，店铺外键，商品外键，数量
CREATE TABLE INVERTORY(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
	STORE_ID BIGINT COMMENT '店铺外键' REFERENCES STORE (ID),
	GOODS_ID BIGINT COMMENT '商品外键' REFERENCES GOODS (ID),
	PRICE DECIMAL(15,3) COMMENT '单价 单位（元）',
	NUMBER DOUBLE COMMENT '库存数量',
 	CONSTRAINT FK_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORE (ID),
	CONSTRAINT FK_GOODS_ID FOREIGN KEY (GOODS_ID)	REFERENCES GOODS (ID)
)ENGINE=INNODB  DEFAULT CHARSET=UTF8 COMMENT='库存信息';


-- 订单信息
-- 主键，订单编号，买家(人员外键)，订单总金额，订单状态，订单是否作废，生成日期，交易成功时间
CREATE TABLE GOODS_ORDER(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
	ORDER_NUM VARCHAR(32)  COMMENT '订单编号',
	PEOPLE_ID BIGINT COMMENT '买家(人员外键)' REFERENCES PEOPLE(ID),
	TOTAL_MONEY DECIMAL(15,3) COMMENT '订单总金额',
	ADD_TIME DATETIME COMMENT '生成日期  yyyy-MM-dd HH:mm:ss',
	SUCCESS_TIME DATETIME COMMENT '交易成功时间  yyyy-MM-dd HH:mm:ss',
	ORDER_STATUS TINYINT(2) COMMENT '订单状态 0--未支付，1--支付成功，2--支付失败',
	IS_INVALID TINYINT(1) DEFAULT 1 COMMENT '订单是否作废 0--作废，1--不作废',
	CONSTRAINT FK1_PEOPLE_ID FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE (ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '订单信息';


-- 订单详情
-- 主键，订单编号，买家(人群外键),店铺外键,商品外键,购买数量	,单价,商品总金额,
-- 生成日期，交易成功时间，发货时间，订单状态，是否作废
CREATE TABLE ORDER_DETAIL(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键id',
 	ORDER_NUM VARCHAR (32)  COMMENT '订单编号',
  PEOPLE_ID BIGINT COMMENT '买家(人群外键)' REFERENCES PEOPLE (ID),
 	STORE_ID BIGINT COMMENT '店铺外键' REFERENCES STORE (ID),
 	GOODS_ID BIGINT COMMENT '商品外键' REFERENCES GOODS (ID),
	GOODS_ORDER_ID BIGINT COMMENT '订单外键' REFERENCES GOODS_ORDER(ID),
	NUMBER DOUBLE COMMENT '购买数量',
	GOODS_PRICE DECIMAL(15,3) COMMENT '单价 单位（元）',
	GOODS_AMOUNT DECIMAL(15,3) COMMENT '商品总金额 单位（元）',
	ADD_TIME DATETIME COMMENT '生成日期  yyyy-MM-dd HH:mm:ss',
	SUCCESS_TIME DATETIME COMMENT '交易成功时间  yyyy-MM-dd HH:mm:ss',
	DELIVERY_TIME DATETIME COMMENT '发货时间  yyyy-MM-dd HH:mm:ss',
	ORDER_STATUS TINYINT(2) DEFAULT 0 COMMENT '订单状态 0--未支付，1--支付成功，2--支付失败，3--发货中，4--订单完成',
	IS_INVALID TINYINT(1) DEFAULT 1 COMMENT '订单是否作废 0--作废，1--不作废',
 	CONSTRAINT FK2_PEOPLE_ID FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE (ID),
 	CONSTRAINT FK2_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORE (ID),
 	CONSTRAINT FK2_GOODS_ID FOREIGN KEY (GOODS_ID) REFERENCES GOODS (ID),
	CONSTRAINT FK2_GOODS_ORDER_ID FOREIGN KEY(GOODS_ORDER_ID) REFERENCES GOODS_ORDER(ID)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '订单详情';


-- 流水表
-- 支付流水：主键id,流水号,人员外键,金额,流水类型,流水生成时间,订单详情外键,订单信息外键
CREATE TABLE PAY_FLOW(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键id',
	FLOW_NUM VARCHAR(32)  COMMENT '流水号',
	PEOPLE_ID BIGINT COMMENT '(人员外键)' REFERENCES PEOPLE (ID),
	MONEY DECIMAL(15,3) COMMENT '金额 单位（元）',
	FLOW_TYPE TINYINT(2) DEFAULT '1' COMMENT '流水类型 1--支出，2--收入',
	CREATE_TIME DATETIME  COMMENT '流水生成时间  yyyy-MM-dd HH:mm:ss',
	ORDER_DETAIL_ID BIGINT COMMENT '订单详情外键' REFERENCES ORDER_DETAIL(ID),
	GOODS_ORDER_ID BIGINT COMMENT '订单信息外键' REFERENCES GOODS_ORDER(ID),
 	CONSTRAINT FK3_PEOPLE_ID FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE (ID),
	CONSTRAINT FK3_ORDER_DETAIL_ID FOREIGN KEY (ORDER_DETAIL_ID) REFERENCES ORDER_DETAIL(ID),
	CONSTRAINT FK3_GOODS_ORDER_ID FOREIGN KEY (GOODS_ORDER_ID) REFERENCES GOODS_ORDER(ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '支付流水';


-- 物流信息表
-- 主键，物流单号，物流状态，订单信息外键，物流信息表，发货人电话，发货地址，收货人姓名，收货人电话，收货人地址
CREATE TABLE LOGISTICS_INFO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	LOGISTICS_NUM VARCHAR(30) NOT NULL UNIQUE COMMENT '物流单号',
	LOGISTICS_STATE TINYINT(2) COMMENT'物流状态 1-以揽件 2-运输中 3-已到达 4-等待配送 5-配送中 6-已签收',
	ORDER_DETAIL_ID  BIGINT COMMENT'订单信息表 外键',
	DELIVER_NAME VARCHAR(50) COMMENT'物流信息表',
	DELIVER_PHONE VARCHAR(15) COMMENT'发货人电话',
	DELIVER_ADDRESS VARCHAR(100) COMMENT'发货地址',
	CONSIGNEE_NAME VARCHAR(50) COMMENT'收货人姓名',
	CONSIGNEE_PHONE VARCHAR(15) COMMENT'收货人电话',
	CONSIGNEE_ADDRESS VARCHAR(100) COMMENT'收货人地址',
	CONSTRAINT FK_LOGISTICS_INFO_ORDER_DETAIL FOREIGN KEY(ORDER_DETAIL_ID) REFERENCES ORDER_DETAIL(ID)
)ENGINE=INNODB COMMENT'物流信息表';


-- 物流过程
-- 主键，物流信息表，经过地址
CREATE TABLE LOGISTICS_GOBY(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	LOGISTICS_INFO_ID BIGINT NOT NULL COMMENT'物流信息表 外键',
	GOBY_ADDRESS VARCHAR(100) COMMENT'经过地址',
	CONSTRAINT FK_LOGISTICS_GOBY_LOGISTICS_INFO FOREIGN KEY(LOGISTICS_INFO_ID) REFERENCES LOGISTICS_INFO(ID)
)ENGINE=INNODB COMMENT'物流过程';